# Generated by Django 5.0.2 on 2024-02-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_connect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='profile',
        ),
    ]
