# Generated by Django 5.0.2 on 2024-04-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_activityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreview',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityreview', to='login.activity'),
        ),
    ]
