# Generated by Django 5.0.2 on 2024-04-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
