# Generated by Django 5.0.2 on 2024-04-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_activity_latitude_activity_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(default='activity', max_length=255),
        ),
    ]
