# Generated by Django 5.0.2 on 2024-04-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
