# Generated by Django 5.0.2 on 2024-05-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_activity_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
